services:
  polr:
    build:
      context: .
      target: builder
      dockerfile: docker/Dockerfile
    ports: 
      - '8082:80'
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=polr
      - DB_USERNAME=polruser
      - DB_PASSWORD=polaris3d
    volumes:
      - ./app:/var/www/html/
    networks:
      - backnet

  database:
    image: mariadb:10-focal
    command: '--default-authentication-plugin=mysql_native_password'
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/polr-db-password)" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - polr-db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backnet
    environment:
      - MYSQL_USER=polruser
      - MYSQL_PASSWORD=polaris3d
      - MYSQL_DATABASE=polr
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/polr-db-password
      # - MYSQL_ROOT_PASSWORD=somewordpresses
    expose:
      - 3306
      - 33060


volumes:
  db-data:

networks:
  backnet:

secrets:
  polr-db-password:
    file: .secrets/db-password
